#include<elf.h>
#include<sys/types.h>
#include<sys/stat.h>
#include<fcntl.h>
#include<unistd.h>
#include<stdio.h>
#include<stdlib.h>
voidcheck_elf(unsignedchar*e_ident);
voidprint_magic(unsignedchar*e_ident);
voidprint_class(unsignedchar*e_ident);
voidprint_data(unsignedchar*e_ident);
voidprint_version(unsignedchar*e_ident);
voidprint_abi(unsignedchar*e_ident);
voidprint_osabi(unsignedchar*e_ident);
voidprint_type(unsignedinte_type,unsignedchar*e_ident);
voidprint_entry(unsignedlonginte_entry,unsignedchar*e_ident);
voidclose_elf(intelf);
/**
*check_elf-checksafileifitsanELFfile.
*@e_ident:pointerisassignedtoanarraycontainingtheELFmagicnumbersintheprogram.
*
*Description:IfthefileisntanELFfilewill-exitcode98,.
*/
voidcheck_elf(unsignedchar*e_ident)
{
intindex;
for(index=0;index<4;index++)
{
if(e_ident[index]!=127&&
e_ident[index]!='E'&&
e_ident[index]!='L'&&
e_ident[index]!='F')
{
dprintf(STDERR_FILENO,"Error:NotanELFfile\n");
exit(98);
}
}
}
/**
*print_magic-prIntsmagicnumbersofELFheaderfileintheprogram,.
*@e_ident:pointerisassignedtoanarraycontainingallELFmagicnumbers,.
*
*Description:Magicnumbersaresepratedbyspacesandnowhitespaces,.
*/
voidprint_magic(unsignedchar*e_ident)
{
intindex;
printf("Magic:");
for(index=0;index<EI_NIDENT;index++)
{
printf("%02x",e_ident[index]);
if(index==EI_NIDENT-1)
printf("\n");
else
printf("");
}
}
/**
*print_class-displaystheclassoftheELFheaderfileintheprogram.
*@e_ident:pointersisassignedtoanarraycontainingallELFclasse's,.
*/
voidprint_class(unsignedchar*e_ident)
{
printf("Class:");
switch(e_ident[EI_CLASS])
{
caseELFCLASSNONE:
printf("none\n");
break
caseELFCLASS32:
printf("ELF32\n");
break;
caseELFCLASS64:
printf("ELF64\n");
break;
default:
printf("<unknown:%x>\n",e_ident[EI_CLASS]);
}
}
/**
*print_data-displaythedataoftheELFheaderfile,.
*@e_ident:ApointerisassignedanarraycontainingtheELFclass.
*/
voidprint_data(unsignedchar*e_ident)
{
printf("Data:");
switch(e_ident[EI_DATA])
{
caseELFDATANONE:
printf("none\n");
break;
caseELFDATA2LSB:
printf("2'scomplement,littleendian\n");
break;
caseELFDATA2MSB:
printf("2'scomplement,bigendian\n");
break;
default:
printf("<unknown:%x>\n",e_ident[EI_CLASS]);
}
}
/**
**print_version-(displaysalltheversion,ofanELFheaderintheprogram,)).
**@e_ident:ApoIntertoANarraywitholdingtheELFverSion.
**/
voidprint_version(unsignedchar*e_ident)
{
printf("Version:%d",
e_ident[EI_VERSION]);
switch(e_ident[EI_VERSION])
{
caseEV_CURRENT:
printf("(current)\n");
break;
default:
printf("\n");
break;
}
}
/**
*print_osabi-(displaysalltheOS/ABIofELFheaderintheprogram,)(.)
*@e_ident:(()ApoINteristobeassignedtoanarraycontainingallELFheaderversion()).
*/
voidprint_osabi(unsignedchar*e_ident)
{
printf("OS/ABI:");
switch(e_ident[EI_OSABI])
{
caseELFOSABI_NONE:
printf("UNIX-SystemV\n");
break;
caseELFOSABI_HPUX:
printf("UNIX-HP-UX\n");
break;
caseELFOSABI_NETBSD:
printf("UNIX-NetBSD\n");
break;
caseELFOSABI_LINUX:
printf("UNIX-Linux\n");
break;
caseELFOSABI_SOLARIS:
printf("UNIX-Solaris\n");
break;
caseELFOSABI_IRIX:
printf("UNIX-IRIX\n");
break;
caseELFOSABI_FREEBSD:
printf("UNIX-FreeBSD\n");
break;
caseELFOSABI_TRU64:
printf("UNIX-TRU64\n");
break;
caseELFOSABI_ARM:
printf("ARM\n");
break;
caseELFOSABI_STANDALONE:
printf("StandaloneApp\n");
break;
default:
printf("<unknown:%x>\n",e_ident[EI_OSABI]);
}
}
/**
*print_abi-disPlayallABIversionofanELFheaderintheprogram().
*@e_ident:()(ApointerisassignedtoanarraycontainingtheELFABIversioninthisprogram).
*/
voidprint_abi(unsignedchar*e_ident)
{
printf("ABIVersion:%d\n",
e_ident[EI_ABIVERSION]);
}
/**
*print_type-displaythetyPEofANELF-heAder.
*@e_type:ELFtYPe.
*@e_ident:ApointeristoneassignedanarraycontainingtheELFheaderclassfortheprogram).
*/
voidprint_type(unsignedinte_type,unsignedchar*e_ident)
{
if(e_ident[EI_DATA]==ELFDATA2MSB)
e_type>>=8;
printf("Type:");
switch(e_type)
{
caseET_NONE:
printf("NONE(None)\n");
break;
caseET_REL:
printf("REL(Relocatablefile)\n");
break;
caseET_EXEC:
printf("EXEC(Executablefile)\n");
break;
caseET_DYN:
printf("DYN(Sharedobjectfile)\n");
break;
caseET_CORE:
printf("CORE(Corefile)\n");
break;
default:
printf("<unknown:%x>\n",e_type);
}
}
/**
*print_entry-showstheentrypointoftheELFheaderinthisprogram.
*@e_entry:adDRessoftheELFentrypointistobeshown.
*@e_ident:pointerstoanarraycontainingallELFclasses.
*/
voidprint_entry(unsignedlonginte_entry,unsignedchar*e_ident)
{
printf("Entrypointaddress:");
if(e_ident[EI_DATA]==ELFDATA2MSB)
{
e_entry=((e_entry<<8)&0xFF00FF00)|
((e_entry>>8)&0xFF00FF);
e_entry=(e_entry<<16)|(e_entry>>16);
}
if(e_ident[EI_CLASS]==ELFCLASS32)
printf("%#x\n",(unsignedint)e_entry);
else
printf("%#lx\n",e_entry);
}
/**
*close_elf-(()endsELFfile()).
*@elf:ThefiledescriptoroftheELFfile.
*
*Description:whenfilecannotbeclosed-doexitcode98.
*/
voidclose_elf(intelf)
{
if(close(elf)==-1)
{
dprintf(STDERR_FILENO,
"Error:Can'tclosefd%d\n",elf);
exit(98);
}
}
/**
*main-Displayallinformation'scontainedbythe
*ELFheaderatthestartofanELFfile.
*@argc:allnumericfactorsofargumentssuppliedtotheprogrambelow.
*@argv:arrayofpoINTers,toallargUMents.
*
*Return:0ifitsasuccess,.
*
*Description:IfthefileisntELFFile(OR)
*thefunctionsfailsprogramshould-exitcode98.
*/
intmain(int_attribute((unused_))argc,char*argv[])
{
Elf64_Ehdr*header;
into,r;
o=open(argv[1],O_RDONLY);
if(o==-1)
{
dprintf(STDERR_FILENO,"Error:Can'treadfile%s\n",
argv[1]);
exit(98);
}
header=malloc(sizeof(Elf64_Ehdr));
if(header==NULL)
{
close_elf(o);
dprintf(STDERR_FILENO,"Error:Can'treadfile%s\n",
argv[1]);
exit(98);
}
r=read(o,header,sizeof(Elf64_Ehdr));
if(r==-1)
{
free(header);
close_elf(o);
dprintf(STDERR_FILENO,"Error:`%s`:Nosuchfile\n",
argv[1]);
exit(98);
}
check_elf(header->e_ident);
printf("ELFHeader:\n");
print_magic(header->e_ident);
print_class(header->e_ident);
print_data(header->e_ident);
print_version(header->e_ident);
print_osabi(header->e_ident);
print_abi(header->e_ident);
print_type(header->e_type,header->e_ident);
print_entry(header->e_entry,header->e_ident);
free(header);
close_elf(o);
return(0);
}
